spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_db
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      filters: stat,wall,slf4j
      stat-view-servlet:
        enabled: true
        login-password: 123456
        login-username: admin
        reset-enable: false
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      aop-patterns: com.example.admin.*
      #      监控包下的组件spring
      filter:
        stat:
          slow-sql-millis: 1000
          #慢查询
          log-slow-sql: true
          enabled: true
        wall:
          enabled: true

#整合mybatis
  jdbc:
    template:
      query-timeout: 3
  boot:
    admin:
      client:
        url: http://localhost:8888
        instance:
          prefer-ip: true # 使用ip注册进来
#    filters: stat,wall
#    max-active: 12
#      设置时间(s),超过后算超时
#    type: com.zaxxer.hikari.HikariDataSource//默认的

#mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml
#  mapper-locations: classpath:mybatis/mapper/*.xml
##  configuration:
##    map-underscore-to-camel-case: true

# management 是所有actuator的配置



management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: true
  endpoint:
    health:
      show-details: always

info:
  appName: boot-admin
  app-version: 1.0.0
  mavenProjectName: @project.artifactId@
