spring:
  mvc:
#    静态资源访问前缀
    static-path-pattern: /res/**
#    开启隐藏域方法实现delete和put方法
    hiddenmethod:
      filter:
        enabled: true
#    开启参数内容协商
    contentnegotiation:
      favor-parameter: true

  web:
    resources:
#      静态资源访问路径
      static-locations: classpath:/picture
#      启用静态资源访问
      add-mappings: true
      cache:
        period: 11000

